### ISSUE TITLE
exception during start

### ISSUE THREAD

**Issue by jkremser** [jvm-operators/scala-example-operator#1]
```
2018-08-08 10:36:27 WARN  WatchConnectionManager:195 - Exec Failure: HTTP 400, Status: 400 - unable to parse requirement: found '.io/kind', expected: '=', '!=', '==', 'in', notin'
java.net.ProtocolException: Expected HTTP 101 response but was '400 Bad Request'
	at okhttp3.internal.ws.RealWebSocket.checkResponse(RealWebSocket.java:219)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:186)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-08-08 10:36:27 INFO  AbstractOperator:190 - Watcher closed in namespace myproject
2018-08-08 10:36:27 ERROR Entrypoint:109 - 'ispn' operator in namespace myproject failed to start
io.fabric8.kubernetes.client.KubernetesClientException: unable to parse requirement: found '.io/kind', expected: '=', '!=', '==', 'in', notin'
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onFailure(WatchConnectionManager.java:199)
	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:546)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:188)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jkremser** [comment]
this was caused by spaces in the prefix

```
@Operator(forKind = "ispn", prefix = "radanalytics  .io")
```
